### ISSUE TITLE
VID does not take effect when building hgraph index

### ISSUE THREAD

**Issue by Carrot-77** [antgroup/vsag#189]
**Describe the bug**
VID does not take effect when building hgraph index

**To Reproduce**
Codes to reproduce the behavior:
```cpp
// first create hgraph index
index = vsag::Factory::CreateIndex("hgraph", index_parameters.dump())
//  vid start at 100000
int num_vectors = 10000;
   for (int64_t i = 0; i < num_vectors; ++i) {
        ids[i] = i + 100000;
    }
    for (int64_t i = 0; i < dim * num_vectors; ++i) {
        vectors[i] = distrib_real(rng);
    }

// second build
auto dataset = vsag::Dataset::Make();
    dataset->Dim(dim)
    ->NumElements(size)
    ->Ids(ids)
    ->Float32Vectors(vectors)
    ->Owner(false);
    ret = hnsw->build_index(dataset);

// third search
query->NumElements(1)->Dim(dim)->Float32Vectors(query_vector)->Owner(false);
    ret = hnsw->knn_search(query, topk, search_parameters.dump(), dist, ids, result_size, filter);
```
The vids returned in the query results are all less than 1w

**Environment**
- OS(e.g. `Ubuntu 22.04`): 
- vsag version(master): 
- compiler version(e.g. `GCC 11.4.0`):
- interface(`cpp`):

**Expected behavior**
In fact, the number of vids in the query result should be between 100,000 and 110,000

**Screenshots**
![image](https://github.com/user-attachments/assets/1d70ab59-3e1a-4f52-a175-44f8f8845e96)

**Comment by wxyucs** [comment]
@LHT129  is working on this issue.
