### ISSUE TITLE
hnsw parameter “sq_num_bits” and “redundant_rate” in ann-benchmark cannot be found in vsag source

### ISSUE THREAD

**Issue by Patrick16262** [antgroup/vsag#193]
Is those parameter works?

**Comment by wxyucs** [comment]
Hi @Patrick16262, the pyvsag that summit to the ann-benchmarks repo is packaged on this branch (https://github.com/antgroup/vsag/tree/annbenchmarks-rs-horizontal-cut-830). The optimized HNSW has been separated into several features that are now being developed to make it pluggable. The first available feature is "HGraph Index" that is already been merged into the main branch.

**Comment by Patrick16262** [comment]
Thank you! I have another question. I ran an ANN benchmark on HNSW using sift-128-euclidean, and the performance is much lower than that of glass. Is this correnct?
![sift-128-euclidean](https://github.com/user-attachments/assets/e05e6793-5d9c-412b-b983-03dd96346b3f)

**Comment by Patrick16262** [comment]
@wxyucs I ran this on AMD Ryzen Threadripper 3990X 64-Core Processor which support sse sse2 avx2. The RAM is 128G. I ran with option `--parallelism 6` .

**Comment by wxyucs** [comment]
@Patrick16262 Yes, it is similar to our test result. We made some optimizations for the 960d and 1000+d datasets, they may not work very well on sift the 128d dataset. But it is also better than the original HNSW algorithm. :)

If you want to get better performance on more different dimension datasets, please follow us. We will continue to implement more optimizations in the next future.

**Comment by Patrick16262** [comment]
thanks!
