### ISSUE TITLE
resize index core dump

### ISSUE THREAD

**Issue by wu-xingying** [antgroup/vsag#70]
**Describe the bug**
May occur when memory alloc failed
![image](https://github.com/user-attachments/assets/a9cf4f5d-19b1-4d57-9756-60bd8ba32b77)

**To Reproduce**
Codes to reproduce the behavior:
```cpp
// paste codes here

```

**Environment**
- OS(e.g. `Ubuntu 22.04`): 
- vsag version(e.g. `v0.11.0` or `7f94a27`): 
- compiler version(e.g. `GCC 11.4.0`):
- interface(`cpp` or `python`):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wxyucs** [comment]
@inabao is working on this issue.
